all: creat deposit withdraw change balance
	@echo it is fine

creat : 
	cc -o creat creat.c

deposit :
	cc -o deposit deposit.c

withdraw :
	cc -o withdraw withdraw.c

change :
	cc -o change change.c

balance :
	cc -o balance balance.c
